before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl

production:
    type: deploy
    script:
        - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_API_KEY
    only:
        - master